### ISSUE TITLE
Goal Statement

### ISSUE THREAD

**Issue by Atarust** [movabo/science-revisioning#7]
Define our project goal (1 page). More information tba.

**Comment by movabo** [comment]
* Ziele genauer definiert
 * Beispiel

**Comment by movabo** [comment]
https://github.com/movabo/science-revisioning/issues/5

**Comment by Atarust** [comment]
The goal statement can be seen here:
[DASP_ Goal Statement.pdf](https://github.com/movabo/science-revisioning/files/3874443/DASP_.Goal.Statement.pdf)
